var siteData = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "name": "Trammps Bar", "year": "1976-90s", "emergence": "The first gay owned club in Lansing, Trammps was the Studio 54 of the gay scene, often competing with Joe Covello's next door.", "departure": "demolished in the 90s after the city bought the block of businesses for a new baseball stadium.", "address": null, "website": null, "photo": "<img src=\"https:\/\/raw.githubusercontent.com\/smahnke\/QR-Map3\/gh-pages\/trammps.jpg\" width=\"500\" height=\"361\" frameborder=\"0\" allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen><\/>", "other_tags": "\"addr:city\"=>\"Philadelphia\",\"addr:housenumber\"=>\"302\",\"addr:postcode\"=>\"19122\",\"addr:street\"=>\"West Berks Street\",\"amenity\"=>\"social_facility\",\"contact:phone\"=>\"215-339-0900\",\"social_facility\"=>\"food_bank\",\"website\"=>\"http:\/\/www.philabundance.org\"" }, "geometry": { "type": "Point", "coordinates": [ -84.545577, 42.734447 ] } },
{ "type": "Feature", "properties": { "name": "Salus Center", "year": "2017-", "emergence": "to be filled...", "departure": "N/A", "address": "624 E. Michigan, Lansing 48912", "website": "http://www.saluscenter.org", "photo": null, "other_tags": "\"addr:city\"=>\"Lansing\",\"addr:housenumber\"=>\"624\",\"addr:postcode\"=>\"48912\",\"addr:street\"=>\"E Michigan Street\",\"amenity\"=>\"social_facility\",\"contact:phone\"=>\"517-339-4593\",\"social_facility\"=>\"community_center\",\"website\"=>\"http:\/\/http://www.saluscenter.org\"" }, "geometry": { "type": "Point", "coordinates": [ -84.543383, 42.733345 ] } },
{ "type": "Feature", "properties": { "name": "Velvet Fingers", "year": "70s-1993", "emergence": "Formerly known the Velvet Touch Massage Parlor, this adult store was just one of the many public sexual establishments on the 500 block, such as the New Art Theatre, Capital News Adult Bookstore, Pleasure Chest Adult Bookstore, the Sir Club and Superstar Videos/S'il Vous Plait.", "departure": "The last of the businesses standing on the 'Sin Street' 500 block, Velvet Fingers was demolished in 1993 to make way for a new baseball stadium. According to Dozzier (2015), 'the north side of the block is now occupied by the Cooley Law School Stadium, a mix of retail, commercial, and residential development.'", "address": "527 E. Michigan, Lansing 48912", "website": "N/A", "photo": "img src=\"https:\/\/raw.githubusercontent.com\/smahnke\/QR-Map3\/gh-pages\/Velvet.png\" width=\"500\" height=\"361\" frameborder=\"0\" allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen><\/>", "other_tags": "\"addr:city\"=>\"Lansing\",\"addr:housenumber\"=>\"527\",\"addr:postcode\"=>\"48912\",\"addr:street\"=>\"E Michigan Street\",\"amenity\"=>\"social_facility\",\"contact:phone\"=>\"517-339-4593\",\"social_facility\"=>\"community_center\",\"website\"=>\"" }, "geometry": { "type": "Point", "coordinates": [ -84.544727, 42.733786 ] } },
]
};
